name: appstrument
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  archive: ^3.3.1
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.5
  protobuf: ^2.1.0
  web_socket_channel: ^2.2.0
  process_run: ^0.12.3+2
  file_picker: ^5.2.0+1
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/java/
